# Generated by Django 5.2.10 on 2026-05-19 13:44

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('session_pin', models.CharField(default=core.models.generate_session_pin, max_length=5, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditorSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=64)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('is_online', models.BooleanField(default=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_sessions', to='core.auditsession')),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auditor_id', models.CharField(db_index=True, max_length=64)),
                ('zone', models.CharField(db_index=True, max_length=64)),
                ('barcode', models.CharField(db_index=True, max_length=64)),
                ('delta', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('synced', models.BooleanField(default=False)),
                ('is_unlisted', models.BooleanField(default=False)),
                ('unlisted_label', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='core.auditsession')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['session', 'barcode'], name='core_auditl_session_8f319a_idx'), models.Index(fields=['session', 'auditor_id'], name='core_auditl_session_ba4324_idx'), models.Index(fields=['session', 'zone'], name='core_auditl_session_dd96c0_idx'), models.Index(fields=['synced'], name='core_auditl_synced_32ccfe_idx')],
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=64)),
                ('product_name', models.CharField(max_length=500)),
                ('expected_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=255)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='core.auditsession')),
            ],
            options={
                'ordering': ['product_name'],
                'indexes': [models.Index(fields=['session', 'barcode'], name='core_catalo_session_74064d_idx')],
                'unique_together': {('session', 'barcode')},
            },
        ),
    ]
