# Generated by Django 5.2.10 on 2026-05-21 01:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecountTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='core.auditorsession')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recount_tasks', to='core.auditsession')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('session', 'barcode', 'status')},
            },
        ),
    ]
