# Generated by Django 5.2.10 on 2026-05-25 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recounttask'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlogentry',
            name='core_auditl_session_dd96c0_idx',
        ),
        migrations.RemoveField(
            model_name='auditlogentry',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='auditorsession',
            name='zone',
        ),
    ]
